FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
RUN pip install transformers
RUN mkdir /app
WORKDIR /app
RUN apt update
RUN apt install -y git
RUN git clone --branch 0.0.4 --single-branch https://github.com/matteopt/geoguessr-detect-web
WORKDIR /app/geoguessr-detect-web
CMD ["python", "server.py"]
